### ISSUE TITLE
Disable bots if disabled on SSCAIT and last update > x months

### ISSUE THREAD

**Issue by Bytekeeper** [Bytekeeper/basil#16]
Bots disabled on SSCAIT are currently not disabled on BASIL (otherwise tournaments on SSCAIT will also disable a major part of BASIL).
Yet, disabling bots should still be possible. Therefore, if a bot is marked as disabled on SSCAIT and not updated since a while, disable them for BASIL as well.

**Comment by Bytekeeper** [comment]
SSCAIT tournament will run for 1.5-2months. So I'll take 65 days to have some margin.

**Comment by krasi0** [comment]
This approach makes perfect sense. BASIL is a distinct ladder and should operate as such :)
