### ISSUE TITLE
crosstable colors

### ISSUE THREAD

**Issue by MicroDK** [Bytekeeper/basil#18]
Let the colors blend between green / white / red (white = 50%) instead of blending between red / green... it will be easier to read the numbers and look better. ;)

**Comment by Bytekeeper** [comment]
It's still different from https://cachedsscaitscores.krasi0.com/eloRatings/crosstable.php in that yellow seems to be used for `0-0` and white for `x-x` for x > 0.
That coloring doesn't make sense to me, as `0-0` holds no information and should be white while `x-x` could be yellow (as in between red and green on a color wheel).
