### ISSUE TITLE
Add ability to see the full date range in charts

### ISSUE THREAD

**Issue by chriscoxe** [Bytekeeper/basil#23]
Add ability to see the full date range in charts.  Currently it seems to only show the last month.  E.g. add a button to zoom out to show a wider date range (or the full date range), and ability to drag horizontally with the mouse to zoom in.

**Comment by MicroDK** [comment]
Preferable, be able to change date interval (from -> to)

**Comment by Bytekeeper** [comment]
@chriscoxe Zooming and panning seems a bit buggy so I left it out. Start + End date should be more than enough.

**Comment by chriscoxe** [comment]
Thanks!
