### ISSUE TITLE
Ability to sort crosstable according to a selected bot's best to worst opponent matchups

### ISSUE THREAD

**Issue by chriscoxe** [Bytekeeper/basil#26]
To make it easier to see which opponents a particular bot is weak against, in the crosstable, would be helpful if whenever you click on a particular bot name, it sorts the rows/columns of the table according to that bot's results (breaking ties using the original ranking).

I.E. if you click on a selected bot, supposing the selected bot's average win rate is 59.06%, it would show the bots that have the win rate >= 59.06% against it as top-most (& left-most) in the table, then the selected bot, then the bots that have the win rate < 59.06% against it as bottom-most (& right-most) in the table.  Ties can be broken by magnitude if some bots have been played more than others (e.g. 8 - 0 then 7 - 0 then 9 - 1).

**Comment by Bytekeeper** [comment]
In the meantime, you can just download the provided CSV.

**Comment by Bytekeeper** [comment]
Actually, I believe this belongs the bot details page and not the crosstable.

**Comment by chriscoxe** [comment]
A start date+time - end date+time selector would also be great that applies to the graphs, to make it easy to look at all the graphs for a particular period that corresponds to particular version of a bot (or just the current version if I haven't kept track of when particular old versions were uploaded).

**Comment by Bytekeeper** [comment]
Which graphs?

**Comment by chriscoxe** [comment]
Any page that has graph(s) could also have a start date+time to end date+time selector.  E.g. the bot details page has a date range selector but currently it only affects the ELO graph.  It could also be changed to affect the Wins Per Map graph and any other graphs you add later, e.g. like the graphs "Win Rate By Opponent", "Win Rate By Map" at Map at https://sscaitournament.com/index.php?action=botDetails&bot=Chris+Coxe.  I think Win Rate By Map is more useful than wins and losses by map, but they are both useful - maybe rate, wins and losses could all be displayed on the same graph.  Thanks for adding a pre-defined date range selector to the crosstable page.  A date+time to date+time selector would allow us to look at whatever period we want, as quite often we are only interested in a specific period (e.g. everything, or just since a particular bot was updated, or just a specific period when an old version of a bot was used).

**Comment by Bytekeeper** [comment]
Hover over any bar in WR/map and you will see the numbers, including WR:
http://basil.bytekeeper.org/bot.html?bot=Chris%20Coxe
I don't even think WR is much more useful than just looking at the bars, but it's there.

For now I'm not planning on adding selectors to all graphs. Those would either require preparing a lot of data or active queries. I have no intention of adding active queries.
There are also no such graphs on the SSCAIT tournament page.
Maybe we can find some middle ground and maybe I will add the possibility for active queries in the medium-far future.

**Comment by chriscoxe** [comment]
Thanks for the response.  I did notice that hovering over a particular bar allows me to see the win rate, which is good.  Just to explain my rationale as a bot developer when I'm actively developing, I try to identify what my bot does worst, and focus on improving that.  I'd rather be able to get a clear visual comparison of the win rate by map or by opponent or by matchup or a combination or whatever, rather than having to hover over each of the 14 maps individually and write down the win rate then sort them myself to figure out which maps my bot is worst on to look for patterns like number of start positions or etc.  I don't find it easy to guage win rate by map visually currently.  Of course, the full data is available, so I could do it in a spreadsheet, but graphs would be very convenient.  It's all good.

**Comment by Bytekeeper** [comment]
@chriscoxe I consider the matchups done with the chart on the bot details page. I'll still try to add WR% as well.
