### ISSUE TITLE
Two digit numbers in crosstable

### ISSUE THREAD

**Issue by MicroDK** [Bytekeeper/basil#30]
Expand cells to support two digit numbers so that users can view matchups scores without clipping: xx-yy

**Comment by Bytekeeper** [comment]
Hmm what browser are you using? Looks fine with xx-yy here. But xxx-yyy will be a problem.

**Comment by MicroDK** [comment]
I am using Chrome on Mac:
<img width="714" alt="screenshot 2019-02-21 at 13 26 22" src="https://user-images.githubusercontent.com/1037224/53168985-4e0c0a80-35dc-11e9-98c2-eac053837915.png">

**Comment by Bytekeeper** [comment]
Ok I guess you have some high DPI screen. Looks find on 1920x1080 chrome. I'll make the columns a bit wider.

**Comment by Bytekeeper** [comment]
@MicroDK Check it out now please.

**Comment by Bytekeeper** [comment]
I guess it's ok.
