### ISSUE TITLE
Add win rate for each map on bot info page

### ISSUE THREAD

**Issue by MicroDK** [Bytekeeper/basil#32]
It would be nice to also have the winrate for each map in the map chart on the bot info page.

**Comment by Bytekeeper** [comment]
I understand, but you can hover to see the actual numbers and the colored blocks are a quite visible winrate indicator.
I'll try to find a way to add it without cluttering the graph. Maybe you could elaborate why it's an improvment to see the actual %?

**Comment by MicroDK** [comment]
It would would be nice to have winrate / lossrate in the popup too.
Because math is difficult. ;)
