### ISSUE TITLE
Filter crosstable based on date

### ISSUE THREAD

**Issue by MicroDK** [Bytekeeper/basil#33]
The crosstable will eventually include all games from the beginning of time, but this can be a bit misleading since bots are updated, bots have bugs and many bots use learning spending many games to find the best strategy.

I propose to add a filter where we can filter the crosstable by date so we only see the crosstable from a specific date.

**Comment by Bytekeeper** [comment]
I don't plan on adding active queries. But I could add some preprocessed ranges. 
Maybe "the last 360, 180 and 90" days?

**Comment by MicroDK** [comment]
Any date filter will work. :)
I suggest last 30, 60, 90, 180 and 360 days.

**Comment by Bytekeeper** [comment]
Instead of 360 there's "everything".

**Comment by Bytekeeper** [comment]
Also added filters: "Enabled" bots and ELO range to show.
