### ISSUE TITLE
Show what race a random bot randomed

### ISSUE THREAD

**Issue by Cmccrave** [Bytekeeper/basil#38]
In the 24h recent games page, could we get an indicator of what race was rolled by random bots? Maybe this is really specific to my case, since my bot is part of ChimeraBot and I'd like to watch my games.

As far as I can tell, BASIL doesn't actually record the pre-selected race. Maybe this could be added? 😄

**Comment by Bytekeeper** [comment]
It actually record the race since a few weeks. Maybe I'll also add the race to the replay file name for random bots.
