### ISSUE TITLE
Game history data download

### ISSUE THREAD

**Issue by chriscoxe** [Bytekeeper/basil#40]
Currently, for game history data, the files available for download (e.g. via the FTP server) are only for the last 24 hours (`games_24h.json`).  `games results.json` and `games results - all games.json` are no longer updated.  Please can the older data files be made available for download (e.g. by FTP), as we discussed on Discord?  JSON is fine, but if it's not easy to figure out what the fields mean or how they are coded, some clarification might be helpful (perhaps there is some kind of schema for it somewhere?).

Note: by "game history data", I am referring to: for each game, the date/time & bot names & races (and who won or whether it was a draw, and the reason e.g. draw because game didn't start) & crash/game timeout/bot timeout data & map & game time & replay details.  And any other relevant info, e.g. I notice there are also now some icons relating to unit data on the "Last 24h" page such as "93 Queens".

**Comment by Bytekeeper** [comment]
Essentially the whole database.
I might reconsider this in the future, but for now I won't do it. For one, there's the problem with huge data packages which will require some special method of distribution (unless I want to clogg my vserver).
Then, I'd like to know what is done with the data and if results will be shared with the community again. I'd rather add more graphs and aggregations for everyone than provide data that is only used by small portion of the community.
That doesn't mean I won't hand out a snapshot of all the data, but not often and especially not on regular intervals.

**Comment by chriscoxe** [comment]
Ok, thanks for considering it.  FYI, the main use cases for me when I am developing my bot would be to:
* Find out the context of games where my bot crashed/timed out.  Especially to be able to identify and get a copy of the replay file produced by the opponent's bot (to see which map, which opponent, and what happened in the game), or at least know the map and opponent then attempt to reproduce the problem locally.
* Know who won for games that lasted 60 minutes (i.e. based on in-game scores), because in this scenario, the bot itself has no way of knowing this (it's adjudicated based on in-game score after each bot's onEnd() method has finished.
* To look for patterns in the history of the data where my bot performed badly, e.g. periods when losing a lot for particular maps or opponents (or combination of opponent and map), or after a particular update of my bot or an opponent bot.
* To look for turning point in the history when my bot learned a way to consistently beat a particular opponent, or vice versa, then see what each bot started doing (e.g. started using a particular build order/strategy, or an update that added new functionality that helped a lot).
