### ISSUE TITLE
New game icons for zerg

### ISSUE THREAD

**Issue by MicroDK** [Bytekeeper/basil#42]
I would like to propose addition of a new game icons for zerg late game units similar to what exists for BC/carriers, M&M and Arbiters:
creation of x infested marines
creation of x zerg guardians (could be the same as for BC/carriers)
creation of x zerg defilers (could be an icon for x amount of spellcasters eg. defilers, hightemplars etc.)
creation of zerg nydus canal

Also, I wonder why Basil has an icon for M&Ms? What is so special about that?

**Comment by Bytekeeper** [comment]
No particular reason.

**Comment by Bytekeeper** [comment]
I added icons for defilers and guardians. Nydus requires more code and I believe only one bot uses them.

**Comment by Bytekeeper** [comment]
For clarification: The icons are only triggered by a certain amount of units. For example, a huge amount of M&M or in this case >= 10 guardians.

**Comment by Bytekeeper** [comment]
For clarification: The icons are only triggered by a certain amount of units. For example, a huge amount of M&M or in this case >= 10 guardians.
